import * as RNFS from '@dr.pogodin/react-native-fs';

export const FLAGS = {
  GLOBAL: 'https://utfs.io/f/ImOWJajUmXfyRKHTpylsELpB6QlYA4OdG9Jfr3hagoCN5Mzt',
  INDIA: 'https://utfs.io/f/ImOWJajUmXfyYCEwdELCDZIMxNG5H27Bouwvb4fyVJrdqj3X',
  ENGLISH: 'https://utfs.io/f/ImOWJajUmXfyN1E0dlnILrEMR3DJQX7OUvixCSHp6YWGNVPc',
  ITALY: 'https://utfs.io/f/ImOWJajUmXfynpGlTaXrTMAELcs2W76PyY4IRJVBXCHOofa5',
};

export const downloadFolder = RNFS.DownloadDirectoryPath + '/OrbixPlay';

export const themes: {name: string; color: string}[] = [
  {
    name: 'OrbixPlay',
    color: '#9447ff96',
  },
  {
    name: 'Hayasaka',
    color: '#00e6e6',
  },
  {
    name: 'Lavender',
    color: '#B2A4D4',
  },
  {
    name: 'Sky',
    color: '#87CEEB',
  },
  {
    name: 'Mint',
    color: '#98FB98',
  },
  {
    name: 'Sunset',
    color: '#FFA07A',
  },
  {
    name: 'Flix',
    color: '#E50914',
  },
  {
    name: 'Material',
    color: '#2196F3',
  },
  {
    name: 'Custom',
    color: '#FFFFFF',
  },
];

export const socialLinks = {
  github: 'https://github.com/angel7544',
  discord: 'https://linkedin.com/in/angel3002',
};

export const EPG_SOURCES = [
  { flag: '🇮🇳', country: 'JioTV EPG', code: 'jio', link: 'https://avkb.short.gy/jioepg.xml.gz' },
  { flag: '🇮🇳', country: 'TataPlay EPG', code: 'tata', link: 'https://avkb.short.gy/tsepg.xml.gz' },
  { flag: '🇮🇳', country: 'TS AIO EPG', code: 'tsaio', link: 'https://avkb.short.gy/epg.xml.gz' },
  { flag: '🇦🇱', country: 'Albania', code: 'al' },
  { flag: '🇦🇷', country: 'Argentina', code: 'ar' },
  { flag: '🇦🇲', country: 'Armenia', code: 'am' },
  { flag: '🇦🇺', country: 'Australia', code: 'au' },
  { flag: '🇦🇹', country: 'Austria', code: 'at' },
  { flag: '🇧🇾', country: 'Belarus', code: 'by' },
  { flag: '🇧🇪', country: 'Belgium', code: 'be' },
  { flag: '🇧🇴', country: 'Bolivia', code: 'bo' },
  { flag: '🇧🇦', country: 'Bosnia & Herzegovina', code: 'ba' },
  { flag: '🇧🇷', country: 'Brazil', code: 'br' },
  { flag: '🇧🇬', country: 'Bulgaria', code: 'bg' },
  { flag: '🇨🇦', country: 'Canada', code: 'ca' },
  { flag: '🇨🇱', country: 'Chile', code: 'cl' },
  { flag: '🇨🇴', country: 'Colombia', code: 'co' },
  { flag: '🇨🇷', country: 'Costa Rica', code: 'cr' },
  { flag: '🇭🇷', country: 'Croatia', code: 'hr' },
  { flag: '🇨🇿', country: 'Czech Republic', code: 'cz' },
  { flag: '🇩🇰', country: 'Denmark', code: 'dk' },
  { flag: '🇩🇴', country: 'Dominican Republic', code: 'do' },
  { flag: '🇪🇨', country: 'Ecuador', code: 'ec' },
  { flag: '🇪🇬', country: 'Egypt', code: 'eg' },
  { flag: '🇸🇻', country: 'El Salvador', code: 'sv' },
  { flag: '🇫🇮', country: 'Finland', code: 'fi' },
  { flag: '🇫🇷', country: 'France', code: 'fr' },
  { flag: '🇬🇪', country: 'Georgia', code: 'ge' },
  { flag: '🇩🇪', country: 'Germany', code: 'de' },
  { flag: '🇬🇭', country: 'Ghana', code: 'gh' },
  { flag: '🇬🇷', country: 'Greece', code: 'gr' },
  { flag: '🇬🇹', country: 'Guatemala', code: 'gt' },
  { flag: '🇭🇳', country: 'Honduras', code: 'hn' },
  { flag: '🇭🇰', country: 'Hong Kong', code: 'hk' },
  { flag: '🇭🇺', country: 'Hungary', code: 'hu' },
  { flag: '🇮🇸', country: 'Iceland', code: 'is' },
  { flag: '🇮🇳', country: 'India', code: 'in' },
  { flag: '🇮🇩', country: 'Indonesia', code: 'id' },
  { flag: '🇮🇱', country: 'Israel', code: 'il' },
  { flag: '🇮🇹', country: 'Italy', code: 'it' },
  { flag: '🇯🇵', country: 'Japan', code: 'jp' },
  { flag: '🇱🇻', country: 'Latvia', code: 'lv' },
  { flag: '🇱🇧', country: 'Lebanon', code: 'lb' },
  { flag: '🇱🇹', country: 'Lithuania', code: 'lt' },
  { flag: '🇱🇺', country: 'Luxembourg', code: 'lu' },
  { flag: '🇲🇰', country: 'Macedonia', code: 'mk' },
  { flag: '🇲🇾', country: 'Malaysia', code: 'my' },
  { flag: '🇲🇹', country: 'Malta', code: 'mt' },
  { flag: '🇲🇽', country: 'Mexico', code: 'mx' },
  { flag: '🇲🇪', country: 'Montenegro', code: 'me' },
  { flag: '🇳🇱', country: 'Netherlands', code: 'nl' },
  { flag: '🇳🇿', country: 'New Zealand', code: 'nz' },
  { flag: '🇳🇮', country: 'Nicaragua', code: 'ni' },
  { flag: '🇳🇬', country: 'Nigeria', code: 'ng' },
  { flag: '🇳🇴', country: 'Norway', code: 'no' },
  { flag: '🇵🇦', country: 'Panama', code: 'pa' },
  { flag: '🇵🇾', country: 'Paraguay', code: 'py' },
  { flag: '🇵🇪', country: 'Peru', code: 'pe' },
  { flag: '🇵🇭', country: 'Philippines', code: 'ph' },
  { flag: '🇵🇱', country: 'Poland', code: 'pl' },
  { flag: '🇵🇹', country: 'Portugal', code: 'pt' },
  { flag: '🇷🇴', country: 'Romania', code: 'ro' },
  { flag: '🇷🇺', country: 'Russia', code: 'ru' },
  { flag: '🇸🇦', country: 'Saudi Arabia', code: 'sa' },
  { flag: '🇷🇸', country: 'Serbia', code: 'rs' },
  { flag: '🇸🇬', country: 'Singapore', code: 'sg' },
  { flag: '🇸🇮', country: 'Slovenia', code: 'si' },
  { flag: '🇿🇦', country: 'South Africa', code: 'za' },
  { flag: '🇰🇷', country: 'South Korea', code: 'kr' },
  { flag: '🇪🇸', country: 'Spain', code: 'es' },
  { flag: '🇸🇪', country: 'Sweden', code: 'se' },
  { flag: '🇨🇭', country: 'Switzerland', code: 'ch' },
  { flag: '🇹🇼', country: 'Taiwan', code: 'tw' },
  { flag: '🇹🇭', country: 'Thailand', code: 'th' },
  { flag: '🇹🇷', country: 'Turkey', code: 'tr' },
  { flag: '🇺🇬', country: 'Uganda', code: 'ug' },
  { flag: '🇺🇦', country: 'Ukraine', code: 'ua' },
  { flag: '🇦🇪', country: 'United Arab Emirates', code: 'ae' },
  { flag: '🇬🇧', country: 'United Kingdom', code: 'gb' },
  { flag: '🇺🇸', country: 'United States', code: 'us' },
  { flag: '🇺🇾', country: 'Uruguay', code: 'uy' },
  { flag: '🇻🇪', country: 'Venezuela', code: 've' },
  { flag: '🇻🇳', country: 'Vietnam', code: 'vn' },
  { flag: '🇿🇼', country: 'Zimbabwe', code: 'zw' }
].map(item => ({ ...item, link: item.link || `https://iptv-epg.org/files/epg-${item.code}.xml` }));
